version: "2"
services:
  client:
    container_name: frontend
    build:
      context: ./client
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./client:/usr/src/app
    ports:
      - 3000:3000
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./api:/usr/src/app
    ports:
      - 8080:8080

